### ISSUE TITLE
Custom allocator support

### ISSUE THREAD

**Issue by sherief** [biojppm/rapidyaml#1]
rapidYAML sounds like a great project! Do you support, or plan to support, custom memory allocators?

**Comment by biojppm** [comment]
Thanks! Yes, you can use your own allocator; there's a C-style API for that, allowing you to set the functions which ryml uses for allocating/freeing memory and error reporting. You can see them in this header: [src/c4/yml/common.hpp](src/c4/yml/common.hpp). When nothing is set, ryml defaults to an implementation using malloc() and free().

```c++

#include <ryml.hpp>

// your custom allocation functions
void* my_allocate(size_t num_bytes, void* hint);
void  my_free(void *mem, size_t num_bytes);

int main()
{
    std::vector<char> srcbuf; // = "{foo: 1}"
    ryml::span src(srcbuf.data(), srcbuf.size()); // a writeable string view

    // call these before using ryml
    ryml::set_allocate_callback(&my_allocate);
    ryml::set_free_callback(&my_free);
    
    //... now ryml will use your functions instead
    auto tree = ryml::parse(src);
    auto root = t.rootref();

    int foo;
    root["foo"] >> foo;
}
```

Also, be aware that ryml is under active development and there will be some breaking changes. These callbacks will be made to receive a data pointer. I'm also contemplating a C++-style allocator, but not as part of ryml's type system -- probably a base class with virtual functions calling these C-style functions.

**Comment by sherief** [comment]
I have a few concerns about this API model. Now, keep in mind that I come from games and other environments with similar low latency requirements that are very strict in some areas, but other areas don't have the same requirements.

- To begin with, there's the issue that this API has two separate calls to set alloc and free functions - this will almost certainly go out of sync. It'd be better to have both function pointers be passed at once, preferably as part of a struct.

- Another problem is that you don't provide a way for the user to pass some context. A void* is the standard way of doing this, just take an opaque pointer from the user and pass it to the alloc / free functions whenever you call them. The user can cast it back to a pointer to an object or a data structure or ignore it or whatever

- A third problem is the fact that this allocator is global. I have an actual use case, the one that caused me to look for an alternative library and discover rapidYAML, where I need to serialize some data really fast every few milliseconds, and I can retry if the serialization fails. In this case I want to give the serializer a linear allocator to use, and if it exhausts it I'm okay with failure and I'll double the allocator capacity on the second try. A linear allocator's alloc() returns a pointer into a block and increments the "next free area" pointer by the amount allocated, and a free() is a no-op, think of it like alloca() and other stack based allocators. This will be very, very fast but I can't use it for serializing a huge amount of state. So in the same app, at the same time, I have a reason to use multiple serializers with multiple allocator strategies.

You can look at libvorbisfile for inspiration. It has a variant of its open() function that takes a callbacks struct ( https://xiph.org/vorbis/doc/vorbisfile/ov_open_callbacks.html ), and I think you could do the same. ryml::parse() could be a wrapper that calls ryml::parse_with_allocator(src, allocator_struct) where the allocator struct is something like 
{
void* user_data;
pfn_alloc alloc_function;
pfn_free free_function;
}

and the signatures for alloc and free accept a void* user_data argument.

What do you think?

**Comment by biojppm** [comment]
I confess I was not considering your use case regarding the different allocators. I opted for a global allocation solution as a regular optional library init step, hence the two different calls. Of course, as you correctly point out, then the sync problem appears if you use these setters from different threads.

Now, if I'm reading you correctly, you are serializing data outside ryml::Tree. Yes? FWIW, the tree does provide a to_arena() template method to simplify serializing your data into its own arena (which is linearly allocated from). You can also reserve the tree's arena before using the tree. So it is conceivable that by judicious calls to `ryml::Tree::reserve()` on the different trees before spawning the threads, you could safely serialize your data into the trees from different threads without ever getting asynchronous allocation calls. I mention this possibility at least as a possible workaround until a more acceptable solution is found. Also, FYI, `ryml::NodeRef::operator<<()` is just a wrapper over the `Tree::to_arena()` method. Indeed, everything in ryml::NodeRef is a wrapper to a tree method. 

As I pointed out above, ryml is still very fresh and under active development, with rough edges in its torso. The allocation functions need of course to receive the void* data pointer (as I also said above). And the solution you propose of using the struct to avoid the separate calls seems satisfactory indeed. I guess the error callback should go there too. It should be noted that to make it per-tree will require adding a callbacks member to the tree. The parser uses a stack with SSO of 16 levels, which is probably enough for most cases, but it may allocate, so it also requires its own callbacks member.

**Comment by sherief** [comment]
Where do you get your arena from?

Trust me on this one: you will never, ever, be able to anticipate the allocation needs of your library's users and cater to it out of the box. Keep in mind that I want to deploy this on PC, PS4, Nintendo Switch, etc.

You can give the user enough control to fit almost every need by making sure you provide the following:
- Allow the user to specify a per-parser allocation context (where a context consists of allocation functions + user-provided "user data" void*)
- Make sure that *all* allocations go through the provided context
- Make sure that a failed allocation is handled properly

I doubt most people will think the cost of having the context as part of the tree will be too much given the flexibility it provides.

**Comment by biojppm** [comment]
Again, to make it clear, I do not need convincing that per-tree allocators is the way to go. I am doing it as we speak.

Having said that, if you allow me, I think you need convincing that you may actually not need this.
Did you have a look at [`ryml::Tree::to_arena()`](https://github.com/biojppm/rapidyaml/blob/4cd034a4d34e02c84f04f9ebd7b5b79bb7af5f2b/src/c4/yml/tree.hpp#L670)? Because it does exactly the try-serialize, resize arena, serialize approach that you mentioned you wanted to do, and does it without error checking involved. And the memory for the arena resize is from the allocator function, of course. ryml does not even try to guess what the user needs. 

Also, it is important to point out that serializing to this arena is opt-in; you can do the serialization in your own blocks of memory (outside of the tree) and pass those as the node's values. Then you can allocate at will without ryml ever needing to know about it. But of course, ryml tries to acommodate this frequent serialization pattern into its regular flow by providing the per-tree arena.

Now the main point. If you (not ryml) have a sure guess of the required arena sizes, you can save the arena reallocation hit at steady state by calling reserve() with a proper arena capacity before spawning your threads. So this way you bypass the need for concurrent calls to the allocator. Of course, if there is even a possibility that the arena will resize at steady state then per-tree allocators really are the way to go.

And again, if you are using the higher-level NodeRef API, you do not need to call the `Tree::to_arena()` method: just stream your variables to the node, and the node itself will serialize to the tree's arena.

HTH.

**Comment by biojppm** [comment]
I just pushed a commit implementing per-tree allocators. Note that the

**Comment by sherief** [comment]
Yup, it looks like this answers all my concerns. Thanks again for this great project!

**Comment by biojppm** [comment]
Great! Closing this. Feel free to reopen if there's something not working. I'll add some tests when I have opportunity.

Also, I'm interested in knowing if rapidYAML lives up to its name under real-world conditions. Let me know if ryml ends up working for you. Benchmark code would be great too. Thanks!

**Comment by sherief** [comment]
You got it! I'll be replacing my code's usage of yaml-cpp with rapidYAML in a side branch and seeing how that goes. I expect the in-situ parsing to make a very significant difference perf-wise.

**Comment by sherief** [comment]
You're going to like this.

In debug builds, parsing a config file went from twenty three milliseconds (yaml-cpp) to eight hundred microseconds (rapidYAML).

In release builds, parsing the same file went from 857 microseconds (yaml-cpp) to 184 microseconds (rapidYAML).

Kudos, and thanks a ton.

**Comment by biojppm** [comment]
Great!!! These numbers are good!

FYI, I found a bug in the parser (for a triply-nested map or something like that). I didn't even get time to make an issue (I'm fairly stretched out right now). I hope to fix it this week.

**Comment by sherief** [comment]
No worries. I will be ramping up the use of rapidYAML in our codebase gradually, so we'll be testing it against more and more complex YAML files. We have an architecture that allows us to swap rapidYAML / yaml-cpp per operation (right now all our save operations go through yaml-cpp due to some API issues with rapidYAML, I'll open a GitHub issue later today or tomorrow).

**Comment by biojppm** [comment]
That's great. Thanks.

**Comment by biojppm** [comment]
I was thinking. How will the difference between yaml-cpp and ryml evolve as the file size increases? I would expect that ryml behaves even better, since it is array based and almost totally sequential, and thus cache-sympathetic. OTOH, usually these kinds of expectations have the annoying habit of being proven wrong...

One way or another I'm highly interested in finding it out, so just give a shout if you come to any conclusion or measurement. Thanks again for the courage of trying out ryml!

**Comment by sherief** [comment]
I would blindly bet money on ryml being a lot faster. The yaml-cpp API is just very performance unfriendly. Like I said, I'll keep testing with larger and larger data sets - I'll let you know how things work out.

**Comment by biojppm** [comment]
Hey @sherief , I need to give you a heads up for your next upstream pull. I decided to rename span/cspan to subs/csubs (as in substring). This also entailed the following:

- the `to_span()/to_cspan()` helper functions have been renamed to `to_subs()/to_csubs()`
- the `subspan()` method has been renamed to `sub()`

Sorry for the inconvenience, but this has been in the backlog, and it's better to do it sooner rather than later.

**Comment by sherief** [comment]
I don't mind the API breaking during development at all. For naming, see issue #7.
