### ISSUE TITLE
Feature request: flat repository structure

### ISSUE THREAD

**Issue by kerrick-lyft** [biojppm/rapidyaml#123]
Hi! :wave:

I was recently evaluating ryml vs [yaml-cpp](https://github.com/jbeder/yaml-cpp) for a project and I decided to go with yaml-cpp, and I thought maybe the reasoning behind this decision would be useful feedback.

Our use-case is that we use YAML to parse data files for tests in CI. These data files can be up to ~500kb each, and we will have 10 or 20 of them (TBD). ryml could save us maybe 5-10 seconds per CI run, which, all else being equal, would be good.

However, because of ryml's code structure (recursively nested Git submodules), the time to pull the code dominates any runtime benefits. Our build system ([Bazel](https://bazel.build/)) does roughly the following in order to clone the ryml code:
```
git clone https://github.com/biojppm/rapidyaml.git --shallow-since='1613428986 +0000' \
&& cd rapidyaml \
&& git submodule update --init --recursive
```
On my machine, this takes about 18 seconds to run.

To fetch yaml-cpp, this is what Bazel does:
```
curl -L https://github.com/jbeder/yaml-cpp/archive/a6bbe0e50ac4074f0b9b44188c28cf00caf1a723.tar.gz \
| tar -xz
```
On my machine, this takes about 2 seconds to run. Note that we can skip dealing with git because all the code is in a single repo, and instead just fetch the tarball from GitHub.

Someday in the future we might configure caching for build inputs, but even then I think Bazel only supports caching binary blobs (like yaml-cpp's `.tar.gz` file) and not Git repositories, so this cost won't go away (it will in fact get worse compared to yaml-cpp).

To get parity with yaml-cpp here, the rapidyaml repo could have a  copy of the c4 source instead of using a submodule. Obviously this has downsides in terms of how easy it is for you to maintain the code in this repo.

Just a suggestion, hopefully you think it's a useful idea :smile:

**Comment by Gei0r** [comment]
Are you re-building your build tools on every CI run? That seems unreasonable.

**Comment by kerrick-lyft** [comment]
We re-compile the source code for our unit tests, which depend on ryml.

**Comment by biojppm** [comment]
Hi @kerrick-lyft, and thanks for the suggestion.

Indeed I really prefer the submodule approach, even if it is nested. I recognize that the clone time may be a downside, but OTOH any other meaningful alternative that continues to be easy for me to track changes would be too much work. As it is my time is rather limited, so I will have to skip your suggestion.

However, maybe you could try parallel cloning of the subrepos? Eg, instead of `git clone --recursive` do a plain `git clone` followed by something like `git fetch --recurse-submodules -j 4`?

More info:
  * https://stackoverflow.com/questions/26023395/how-to-speed-up-parallelize-downloads-of-git-submodules-using-git-clone-recu
  * https://stackoverflow.com/questions/17316257/git-submodule-init-async

**Comment by biojppm** [comment]
BTW, [see also this discussion](https://github.com/biojppm/rapidyaml/discussions/125)

**Comment by biojppm** [comment]
@kerrick-lyft closing; feel free to reopen to address any further points.
