### ISSUE TITLE
Accessing ryml::Location after parsing

### ISSUE THREAD

**Issue by Lemongrass3110** [biojppm/rapidyaml#164]
For usecases like user input validation it would be great to have access to the ryml::Location on NodeRef level.
This allows to tell users where they might have put a wrong value inside the YAML document, even if the structure is valid YAML and was parsed successfully.

yaml-cpp provides this functionality via the [Mark](https://yaml-cpp.docsforge.com/master/api/YAML/Node/Mark/) function.

Since this library focuses on performance it would be okay to enable this via ifdef if necessary as not everyone might need it by default.

For more details check: rathena/rathena#5997

**Comment by biojppm** [comment]
@Lemongrass3110 I have sketched a POC in the PR above. In its current state, the locations are off by some amount because they're only set when a node is added, which due to the yaml parsing state happens in general after the node's source starts. It will be quite a bit of work to make it really correct, and I am not sure I will have the time for this.

But for now this can get you started.

**Comment by cschreib** [comment]
I have been needing this feature has well. Until this is officially supported, there is a way to work around it for most nodes.

First you need to create a line ending offset lookup table like this:
```c++
class file_line_mappings
{
public:

    // Parse the file to locate offsets of line endings;
    // could be overloaded to parse an already existing buffer, like the tree's arena.
    explicit file_line_mappings(const std::string& filename) : filename_(filename)
    {
        std::ifstream stream(filename_);
        if (!stream.is_open())
            return;

        std::string line;
        std::ptrdiff_t prev_pos = 0u;
        while (std::getline(stream, line))
        {
            line_offsets_.push_back(prev_pos);
            prev_pos += line.size() + 1u;
        }
    }

    // Lookup the line endings offsets to get the line/column position from an offset
    std::pair<std::ptrdiff_t,std::ptrdiff_t> get_line_info(std::ptrdiff_t offset) const
    {
        auto iter = std::lower_bound(line_offsets_.begin(), line_offsets_.end(), offset);
        if (iter == line_offsets_.end())
            return std::make_pair(0, 0);

        std::ptrdiff_t line = iter - line_offsets_.begin();
        std::ptrdiff_t column = offset - *iter + 1u;

        return std::make_pair(line, column);
    }

    // Format an offset into "<file>:<line>:<column>"
    std::string get_location(std::ptrdiff_t offset) const
    {
        auto loc = get_line_info(offset);
        if (loc.first == 0)
            return filename_ + ":?:?";
        else
            return filename_ + ":" + std::to_string(loc.first) + ":" + std::to_string(loc.second);
    }

private:

    std::string filename_;
    std::vector<std::ptrdiff_t> line_offsets_;
};
```

Then all you need is figure out the offset of the node inside the input buffer:

```c++
const ryml::Tree& tree = /*...*/; // need a ref to the tree
const ryml::NodeRef& node = /*...*/; // the node for which you want to get the location
const file_line_mappings& mappings = /*...*/; // construct this with the same file/buffer as the tree

std::ptrdiff_t offset = 0;
if (node.has_key())
    offset = node.key().data() - tree.arena().data();
else if (node.has_val())
    offset = node.val().data() - tree.arena().data();

// If the node has a key or value, 'offset' is now the number of bytes since the beginning of the file.
// It can be used with the lookup table to get a nice string showing the location of the node:
std::string location = mappings.get_location(offset);
```

**Comment by biojppm** [comment]
RFC: @Lemongrass3110 @cschreib PR #168 is ready. This is a request for comment.

I ended up using an approach different from the one I suggested above; it would be a large amount of work to have correct. So I ended up using tracking newlines and deltas in the source buffer, in the spirit of what I had suggested earlier in rathena/rathena#5997 and also of the example by @cschreib . The structure is stored in the parser and not the tree, and no particular flags are needed.

The PR is about to be merged, so if you have something to point out it would be better to do it soon. The PR ended up being too large because I also changed other things while I was at it, but you can focus in the PR description, and if you wish, in the files quickstart.cpp, parse.cpp (toward the end) and test_locations.cpp.
