### ISSUE TITLE
Missing exports for symbols in amalgamated header

### ISSUE THREAD

**Issue by biojppm** [biojppm/rapidyaml#182]
_Originally posted by @aviktorov in https://github.com/biojppm/rapidyaml/issues/181#issuecomment-1002268297_

Missing exports are causing link errors:
1. I made header-only rapidyaml library using amalgamate tool;
2. Then I put ryml_all.hpp to the public headers folder and put implementation inside one dll (during that stage I also had to add C4CORE_SHARED C4CORE_EXPORTS RYML_SHARED RYML_EXPORTS compiler definitions in order to have proper symbols exported). I guess amalgamate tool can help with that introducing another define which will set export definitions for both c4core and ryml;
3. After that, I tried to use first dll in another dll which contained specific parsing code and that caused linker errors because of missing exports.

**Comment by biojppm** [comment]
@aviktorov thanks for the patience. The amalgamation logic was merged today so you were the unfortunate one to catch this problem.

Since this is a problem with the amalgamated header, some of the issues are going to have to be addressed by the user. It is easy to have cmake address this problem, but since this is brought inside the user's project, some of the actions to achieve a proper dll from the library are going to have to be taken by the user (ie, you). So it is important to understand what are the proper constraints, so that they are properly documented in the header.

First I guess it is easy to deal with the c4core propagation. Can you confirm that adding these lines to the top of the header eliminates the need to define C4CORE_SHARED or C4CORE_EXPORTS?
```c++
// ... after the license at the top there is this block:
#if defined(RYML_SINGLE_HDR_DEFINE_NOW) && !defined(C4CORE_SINGLE_HDR_DEFINE_NOW)
#define C4CORE_SINGLE_HDR_DEFINE_NOW
#endif

// now, add these lines:
#if defined(RYML_EXPORTS) && !defined(C4CORE_EXPORTS)
#define C4CORE_EXPORTS
#endif

#if defined(RYML_SHARED) && !defined(C4CORE_SHARED)
#define C4CORE_SHARED
#endif
```

Next, can you confirm that in the current state...
1) when building the DLL it is needed to `#define RYML_EXPORTS`
2) when linking with the DLL it is needed to #define RYML_SHARED`
(I'm writing this on a hurry and did not confirm, so maybe I've got the macro names wrong)

If the above is true, then maybe we can make use of `RYML_SINGLE_HDR_DEFINE_NOW` to alleviate the one of the two requirements. Since `RYML_SINGLE_HDR_DEFINE_NOW` means we're building, then requirement 2) can be lifted like this:
```c++
#if defined(RYML_SINGLE_HDR_DEFINE_NOW)
#define RYML_SHARED
#endif
```

Which leaves only the single requirement that `#define RYML_EXPORTS` is needed to compile the amalgamated header into a DLL, and no special requirement to consume the DLL.

**Comment by aviktorov** [comment]
@biojppm yup, I can confirm that c4core macro propagation you suggested works perfectly, thanks! And sorry I didn't mention the Win32 platform in the first post. One more thing I noticed is that ```RYML_EXPORTS``` depends on ```RYML_SHARED``` macro for Win32 so you have to set both macro definitions in the implementation dll.

Also, I didn't set ```RYML_SHARED``` or ```RYML_EXPORTS``` macro in my user dll and it seems to be working just fine. Not sure what's the reason (probably because all symbols can be imported by default?)

I'm not sure if ```RYML_SINGLE_HDR_DEFINE_NOW``` should set those macro definitions automatically, because there might multiple ways you might want to use the library:
1. As a part of a standalone executable. In this case, no symbols need to be exported or imported, I'll just compile the RYML implementation as usual with no additional macro definitions except ```RYML_SINGLE_HDR_DEFINE_NOW```
2. Compile it to a static/dynamic library as internal 3rdparty (no public headers visible) and link to app / dll target. This case is similar to the previous one but automatic macro definition setup (i.e. ```RYML_SHARED``` or ```RYML_EXPORTS```) might interfere with the linker. Not tested this!
3. Compile it a public standalone static library and link to app / dll target. Not sure if having ```__declspec(dllimport)``` attributes by default will interfere with the linker. Need to test this as well!
4. Compile it to as a part of standalone dynamic library with RYML header being a part of dll's public API. This is my case and I need all necessary symbols to be properly marked and exported. This is where you need to care about ```__declspec(dllimport) / __declspec(dllexport)``` attributes on Win32.

This is what I typically do for my Win32 dll code:

```cpp
#ifdef _WIN32
	#define MYLIB_EXPORT __declspec(dllexport)
	#define MYLIB_IMPORT __declspec(dllimport)
#else
	#define MYLIB_EXPORT __attribute__((visibility("default")))
	#define MYLIB_IMPORT 
#endif

#if defined(MYLIB_SHARED_LIBRARY)
	#define MYLIB_API MYLIB_EXPORT 
#else
	#define MYLIB_API MYLIB_IMPORT 
#endif
```

In this sample, my implementation dll should only define a single macro ```MYLIB_SHARED_LIBRARY``` in order to properly export symbols. User code which links to that dll should not set any additional macro definitions. This setup will properly cover cases No.1 & 4 but I'm still not sure about No. 2 & 3 :)
