### ISSUE TITLE
easy way to promote/convert a docref to a tree?

### ISSUE THREAD

**Issue by matt-deboer** [biojppm/rapidyaml#226]
In some cases, I parse a file that happens to have a doc header ('---'),  but it's not interesting, and there's only expected to be a single doc in such files. I want to return a tree where the root node is a DOC.
I see a method to promote a DOC to STREAM--is it possible to go the other direction?

**Comment by biojppm** [comment]
Sorry there is nothing for that

To give some context, the other promotion exists because the parser needs it to handle this case:
```yaml
this is: a map
before: "the --- separator"
---
when the parser sees the separator, it needs to create a stream
to place the two separate docs; the map above will be grafted into
the added stream. Also for consistency reasons,
the map above needs to be tagged as doc, as streams can
only contain docs.
```

Going the other way is not needed, and generally problematic: eg what should be done if the stream contains multiple docs?

I see this more as a userland fix, where something about the data is known. So I suggest to write an adapter in your code to extract the proper. Something like this (untested):
```c++
ryml::NodeRef rootdoc(ryml::Tree &tree)
{
    ryml::NodeRef r = tree.rootref();
    if(r.is_stream())
    {
        assert(r.num_children() == 1);
        r = r.first_child();
    }
    return r;
}
```
And if you want to ensure the stream is not emitted, then just emit the node returned above using the proper `ryml::emit()` overload instead of the one for the tree..

Let me know if this is enough.
