### ISSUE TITLE
Setting a scalar VAL to '...'

### ISSUE THREAD

**Issue by SauliusZ87** [biojppm/rapidyaml#251]
If yaml file contains ... as value without quotes then ryml fails to parse it.  According to online validators, this is a valid file (without quotes).

```
ryml::Tree tree;
ryml::NodeRef root = tree.rootref();
root |= ryml::MAP;
root["test"] = "...";

std::stringstream ss;
ss << tree;
std::string stream_result = ss.str();

ryml::csubstr yml = ryml::csubstr(stream_result.c_str(), stream_result.size());
ryml::parse_in_arena(yml);
```

**Comment by biojppm** [comment]
To be clear, the problem is in emitting and not in parsing.

In these ambiguous cases ryml will not add quotes unless you tell it to (because it would have to scan the string when you set the value).

So do this to make the tree use quotes around `...`:
```c++
root |= ryml::MAP;
root["test"] = "...";
root["test"] |= VALQUO;
```

By the way, there's no need use a slow `stringstream` to get a YAML string. Just do this, which will be much faster:
```c++
std::string s = ryml::emitrs<std::string>(tree);
```
And if you pre-dimension the string, it will be even faster:
```c++
std::string s;
s.resize(1024); // use a large-enough size here
ryml::emit(tree, ryml::to_substr(s));
```
