### ISSUE TITLE
multiline assignment will make the line number is not correctly

### ISSUE THREAD

**Issue by CairoLee** [biojppm/rapidyaml#260]
### Description

When yaml include | mark for multiline assignment, the line number is not correctly

### Example Code
```
ryml::Parser parser;

ryml::Tree tree = parser.parse_in_arena("source.yml", R"(Body:
  - Id: 1
    Name: Apple
    Script: |
      Line One
      Line Two
  - Id: 2
    Name: Cat
    Script: |
      Line One
      Line Two
  - Id: 3
    Name: Dog
    Script: |
      Line One
      Line Two)");

ryml::Location loc = parser.location(tree.rootref());
loc = parser.location(tree["Body"][2]["Name"]);

sprintf("loc.line = %d\n", loc.line + 1);
```

### Expected results
> loc.line = 13

### Current results
> loc.line = 15

**Comment by CairoLee** [comment]
Bump~ the project [rathena](https://github.com/rathena/rathena) already using rapidyaml to parse the yaml file.
in the project, a lot of  data using | to write the item script, incorrectly line numbers can make debugging data errors very difficult

**Comment by biojppm** [comment]
@CairoLee I finally had some time to look at the problem. I'm sorry to say the situation is not good.

This is happening because all multiline scalars (ie all of plain, single-quoted, double-quoted, block-literal or block-folded) have their newline characters filtered during the parsing phase. As currently written, the location data structure is only filled after parsing, which means that by the time this happens, the original newline characters are no longer there, so those lines fail to count for the location. So the reported line is shifted down in some cases and up in some cases, on every multiline scalar. Which means that the shift will compound as the file progresses.

Fixing this will be hard. Expect more time before this gets fixed.

**Comment by biojppm** [comment]
@CairoLee This is now fixed in master. Beware that the fix changes are breaking; you will need to change your code to instantiate the parser with options setting it to track locations. For an example, see the notes added to the changelog or the quickstart file in #307

**Comment by CairoLee** [comment]
@biojppm Thank you for following up on this issue, I noticed what needs to be adjusted.

I will use the latest code and test it later and give you feedback, thanks again.
