### ISSUE TITLE
Lists with unindented items and trailing empty values parse incorrectly

### ISSUE THREAD

**Issue by andrewts129** [biojppm/rapidyaml#274]
Thanks for the library, it's very impressive! I'm trying to create a Ruby gem that wraps it to provide a high performance alternative to the libyaml-based standard library and I'm running into an edge case where rapidyaml seems to incorrectly parse lists that have unindented items with an empty value in the last spot, such as:

```yaml
---
foo:
- bar
-
baz: qux
```

libyaml parses this as:

```
+STR
+DOC ---
+MAP
=VAL :foo
+SEQ
=VAL :bar
=VAL :
-SEQ
=VAL :baz
=VAL :qux
-MAP
-DOC
-STR
```

While rapidyaml produces:

```
+STR
+DOC ---
+MAP
=VAL :foo
+SEQ
=VAL :bar
+MAP
=VAL :baz
=VAL :qux
-MAP
-SEQ
-MAP
-DOC
-STR
```

https://play.yaml.io/main/parser?input=LS0tCmZvbzoKLSBiYXIKLQpiYXo6IHF1eA==

**Comment by biojppm** [comment]
Thanks for the detailed bug report, and kudos for the playground link! Yes, that is definitely a bug. ryml has a problem when the indentless seq in `foo` is ended. FWIW, indenting is enough to get ryml to parse it correctly:

https://play.yaml.io/main/parser?input=LS0tCmZvbzoKICAtIGJhcgogIC0KYmF6OiBxdXg=

Expect some time before this problem is fixed.
