### ISSUE TITLE
Key uniqueness

### ISSUE THREAD

**Issue by a-w50** [biojppm/rapidyaml#342]
Hi,

according to the spec https://yaml.org/spec/1.2.2/, keys should be unique.  Right now rapidyaml doesn't error on duplicated keys (concerning siblings on the same level).  Is this intended and if so, why? If not, would it be possible to fix this and yielding a parsing error?

Thanks!

**Comment by biojppm** [comment]
This is intentional.

Enforcing key uniqueness in the parser or in the tree would cause `N log(N)` parsing complexity (for root children on a mostly flat tree), and would increase code size through increased structural, logical and cyclomatic complexity.

So enforcing uniqueness in the parser would hurt users who may not care about it (they may not care either because non-uniqueness is OK for their use case, or because it is impossible to occur). On the other hand, by doing a post-parse run through the tree, uniqueness is easily enforced by the user if he cares about it

So choosing to not enforce key uniqueness adheres to the spirit of "don't pay for what you don't use".

Now, with this said, I realize that this is not made clear in the Known Limitations of main README. I will add a relevant note about this.

**Comment by a-w50** [comment]
Thanks for this thorough explanation!
