### ISSUE TITLE
What is the result of the ryml::fmt::base64 conversion, and how do I get the result and convert it to std::string

### ISSUE THREAD

**Issue by neomissing** [biojppm/rapidyaml#365]
What is the result of the ryml::fmt::base64 conversion, and how do I get the result and convert it to std::string？

**Comment by biojppm** [comment]
There is a base64 example [in the quickstart](https://github.com/biojppm/rapidyaml/blob/7c0036e7c41318ec75368f9a2b2148c31b3121db/samples/quickstart.cpp#L2573). Start by looking there.

**Comment by biojppm** [comment]
@neomissing did this help?

**Comment by neomissing** [comment]
> @neomissing did this help?

I've already seen the examples, but I can't see what the result of conversion is without implementing std::string to base64. For all the examples, none of them are standard std types, I'd like to add some std conversions to use the demo.

**Comment by biojppm** [comment]
`ryml::fmt::base64()` wraps a buffer with a tag type, such that the deserialization code will dispatch to the base64 decoding functions. Note that it accepts a `substr`. So here's an example using `std::string`:
```c++
        std::string result;
        //...
        len = tree[c.text].deserialize_val(ryml::fmt::base64(ryml::to_substr(result))); // returns the needed size
        if(len > result.size()) // if the size was not enough; resize and call again
        {
            result.resize(len);
            len = tree[c.text].deserialize_val(ryml::fmt::base64(ryml::to_substr(result))); // returns the needed size
        }
        result.resize(len); // trim to the length of the decoded buffer
        CHECK(result == c.text);
```
Note also these are just syntatic wrappers to simplify client code. You can call into the lower level functions without much effort:
```c++
        result.clear(); // this is not needed. We do it just to show that the first call can fail.
        ryml::csubstr encoded = tree[c.text].val();
        CHECK(encoded == c.base64);
        len = base64_decode(encoded, ryml::blob{result.data(), result.size()});
        if(len > result.size())
        {
            result.resize(len);
            len = base64_decode(encoded, ryml::blob{result.data(), result.size()});
        }
        result.resize(len);
        CHECK(result == c.text);
```

**Comment by neomissing** [comment]
Thank you, the test has been modified ok, is there any built-in function to convert the value read by rapidyaml to bool, int and other types of functions, currently can only be converted to std::string for processing, The example given so far is as follows: CHECK(root["foo"].val() == "says you");
CHECK(root["bar"][0].val() == "-2");
CHECK(root["bar"][1].val() == "-3");



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/03/2023 02:05 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [biojppm/rapidyaml] What is the result of the ryml::fmt::base64 conversion, and how do I get the result and convert it to std::string (Issue #365) |

ryml::fmt::base64() wraps a buffer with a tag type, such that the deserialization code will dispatch to the base64 decoding functions. Note that it accepts a substr. So here's an example using std::string:

        std::string result;
        //...
        len = tree[c.text].deserialize_val(ryml::fmt::base64(ryml::to_substr(result))); // returns the needed size
        if(len > result.size()) // if the size was not enough; resize and call again
        {
            result.resize(len);
            len = tree[c.text].deserialize_val(ryml::fmt::base64(ryml::to_substr(result))); // returns the needed size
        }
        result.resize(len); // trim to the length of the decoded buffer
        CHECK(result == c.text);


Note also these are just syntatic wrappers to simplify client code. You can call into the lower level functions without much effort:

        result.clear(); // this is not needed. We do it just to show that the first call can fail.
        ryml::csubstr encoded = tree[c.text].val();
        CHECK(encoded == c.base64);
        len = base64_decode(encoded, ryml::blob{result.data(), result.size()});
        if(len > result.size())
        {
            result.resize(len);
            len = base64_decode(encoded, ryml::blob{result.data(), result.size()});
        }
        result.resize(len);
        CHECK(result == c.text);

**Comment by biojppm** [comment]
It is hard to understand your second question. You say

> can only be converted to std::string for processing

... but that is just false.

You then paste some of the initial examples from the quickstart, but maybe you forgot to continue reading after these, and concluded then that the library or example is defective? Because there is exactly a quick deserialization example a [few lines below that](https://github.com/biojppm/rapidyaml/blob/7c0036e7c41318ec75368f9a2b2148c31b3121db/samples/quickstart.cpp#L344), and detailed examples are to found below the base64 example.

---

It is true that the tree contains only string views, but rapidyaml provides many ways to convert data types directly to `substr` and directly from `csubstr` string views.

Use of `std::string` for conversion is not even needed, nor advised (and much less `std::stringstream`, which has horrible performance; for some corroborating data, see eg the [README for c4core](https://github.com/biojppm/c4core/tree/master/README.md), which shows that `std::stringstream` is hundreds of times slower when converting to/from fundamental types).

I suggest continuing your initial cursory read of the quickstart, which shows many different ways to serialize and deserialize. Start by looking at the uses there of `operator<<(NodeRef, T const&)` for serializing and `operator>>(ConstNodeRef, T&)`  for deserializing. These operators wrap `to_chars()` and `from_chars()`, which in turn wrap the `xtoa()` and `atox()` family of functions. The operators are provided for all the fundamental data types, and you can also define custom operators for your own types; again, the quickstart shows how to do this.
