### ISSUE TITLE
Support Request: Understanding key() during iteration

### ISSUE THREAD

**Issue by floli** [biojppm/rapidyaml#376]
Hello,

I have this tiny program:

```cpp
#define RYML_SINGLE_HDR_DEFINE_NOW

#include "ryml_all.hpp"

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

using std::cout;
using std::endl;

int main(int argc, char* argv[]) {
  std::string input{
      R"(
Sinks:
  - Type: "Colorized" 
    FormatString: "my format string"
    Filter: "AAA Filter"
  - Type: "File"
    FileName: "my file name"
    Filter: "BBB Filter"
    )"};

  ryml::Tree tree = ryml::parse_in_arena(ryml::to_csubstr(input));
  ryml::ConstNodeRef root = tree.rootref();
  ryml::ConstNodeRef sinks = root["Sinks"];
  for (ryml::ConstNodeRef const& sink : sinks) {
    cout << "=============== " << endl;
    cout << sink << endl;
    for (ryml::ConstNodeRef const& child : sink) {
      cout << "----------" << endl;
      cout << child << endl;
      cout << "key = " << child.key().str << endl;
      cout << "val = " << child.val().str << endl;

      cout << "^^^^^^^^^" << endl;
    }
  }

  return 0;
}
```

which produces this output:

```
=============== 
Type: 'Colorized'
FormatString: 'my format string'
Filter: 'AAA Filter'

----------
Type: 'Colorized'

key = Type: "Colorized" 
    FormatString: "my format string"
    Filter: "AAA Filter"
  - Type: "File"
    FileName: "my file name"
    Filter: "BBB Filter"
    
val = Colorized" 
    FormatString: "my format string"
    Filter: "AAA Filter"
  - Type: "File"
    FileName: "my file name"
    Filter: "BBB Filter"
    
^^^^^^^^^
----------
FormatString: 'my format string'

key = FormatString: "my format string"
    Filter: "AAA Filter"
  - Type: "File"
    FileName: "my file name"
    Filter: "BBB Filter"
    
val = my format string"
    Filter: "AAA Filter"
  - Type: "File"
    FileName: "my file name"
    Filter: "BBB Filter"
    
^^^^^^^^^
----------
Filter: 'AAA Filter'

key = Filter: "AAA Filter"
  - Type: "File"
    FileName: "my file name"
    Filter: "BBB Filter"
    
val = AAA Filter"
  - Type: "File"
    FileName: "my file name"
    Filter: "BBB Filter"
    
^^^^^^^^^
=============== 
Type: 'File'
FileName: 'my file name'
Filter: 'BBB Filter'

----------
Type: 'File'

key = Type: "File"
    FileName: "my file name"
    Filter: "BBB Filter"
    
val = File"
    FileName: "my file name"
    Filter: "BBB Filter"
    
^^^^^^^^^
----------
FileName: 'my file name'

key = FileName: "my file name"
    Filter: "BBB Filter"
    
val = my file name"
    Filter: "BBB Filter"
    
^^^^^^^^^
----------
Filter: 'BBB Filter'

key = Filter: "BBB Filter"
    
val = BBB Filter"
    
^^^^^^^^^      
```

making no sense to me.

I except that the outer loop iterates through each block of the sequence that is the value of `Sinks`. This looks valid to me, as the output of `sink` (first output after the `===` line) contains each block.

In the inner loop, I want to iterate over that block, resp. the keys and values of that map. This is the part between `----` and `^^^^`.

This is where my confusion begins.

It looks like that `child.key()` is the entire block at the first iteration, minus the first line at the second, minus the first and second line at the third iteration. Same for the `val()` value.

However, I except it to be the values `Type, FormatString, Filter` and `Type, Filename Filter`. The value of the `child` node itself is fine (first output after `----`), it is what I except.

Can someone help me there?

Thanks!

**Comment by biojppm** [comment]
`ryml::csubstr` is a string view, and as such it is NOT zero-terminated. So if you do `cout << child.key().str` you are printing an unbounded string (or at best bounded at the end of the full source string, if you are lucky). That's why it goes past the end of what you expect: there is no end!

Don't do that.

In your case, just do `cout << child.key()` (notice it does NOT have `.str` at the end), which will write only up to the size of the view. Likewise, `cout << child.val()`:
```c++
#define RYML_SINGLE_HDR_DEFINE_NOW

#include "ryml_all.hpp"

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

int main() {
  std::string input{
      R"(
Sinks:
  - Type: "Colorized"
    FormatString: "my format string"
    Filter: "AAA Filter"
  - Type: "File"
    FileName: "my file name"
    Filter: "BBB Filter"
    )"};

  size_t i = 0;
  ryml::Tree tree = ryml::parse_in_arena(ryml::to_csubstr(input));
  for (ryml::ConstNodeRef const& sink : tree["Sinks"]) {
    std::cout << std::endl;
    for (ryml::ConstNodeRef const& child : sink) {
      std::cout << "Sink[" << i << "]: ~~~" << child.key() << "~~~/~~~" << child.val() << "~~~" << std::endl;
    }
    ++i;
  }

  return 0;
}
```
prints this:
```

Sink[0]: ~~~Type~~~/~~~Colorized~~~
Sink[0]: ~~~FormatString~~~/~~~my format string~~~
Sink[0]: ~~~Filter~~~/~~~AAA Filter~~~

Sink[1]: ~~~Type~~~/~~~File~~~
Sink[1]: ~~~FileName~~~/~~~my file name~~~
Sink[1]: ~~~Filter~~~/~~~BBB Filter~~~
```

Or you could do `k = child.key(); cout.write(k.str, k.len)`, which is what ryml's implementation of `operator<<(ostream&, ryml::csubstr)` does when you call it.

**Comment by biojppm** [comment]
@floli does this answer your question?

**Comment by floli** [comment]
Thanks! Yes, it adds clarity. Just one more question. What is the best method to get a std::string from a node.val() or node.key() ? Is there a way that does not involve using a new variable? e.g. to be used as a parameter (`f(node.key().to_str()` when `void f(std::string)`)

**Comment by biojppm** [comment]
If you want to create a `std::string` there must always be a new variable, as the tree holds only views. If you want syntactic candy to call your `f()` function without having to create a named variable, just define an adapter in your code:
```c++
std::string tostr(ryml::csubstr s) { return {s.str, s.len}; }
```
and then just do `f(tostr(node.key()))`.

But note this is a performance antipattern, as the temporary `std::string` will cause a potential allocation and performance jitter.

I would suggest instead making your `f()` accept directly the `ryml::csubstr`, or if you don't want it to be aware of a ryml type, then just make it accept `f(const char* str, size_t len)` (and again note the `str` is not zero-terminated).

If you are wondering why ryml does not give you a `std::string` it's precisely because it is an antipattern forcing allocation for every string, and further there are projects in embedded where `std::string` just cannot be used. In fact if ryml is rapid it is because in large part it does not use `std::string`.

**Comment by floli** [comment]
Thanks for your explanations!
