### ISSUE TITLE
[Request] Make new release

### ISSUE THREAD

**Issue by marcalff** [biojppm/rapidyaml#421]
Thanks for maintaining rapidyaml.

The last release is 0.5.0, from Dec 22, 2023.

Do you have any plans to make a new release, with an associated git tag ?

This will help repositories downstream to refer to something stable when using rapidyaml.

Given the size of the new parser PR to come in #414, maybe make a release before the merge ?

Regards.

**Comment by biojppm** [comment]
Yes, I intend to do exactly that. ATM my attention is focused on #414 and #411. Once I merge #411, I will finalize #414 and get it ready to merge (but not actually merge). After that is ready, I will search the issues for low hanging fruit, and only then I will make the release.

**Comment by musicinmybrain** [comment]
Since version 0.5.0 of rapidyaml doesn’t quite build with c4core 0.2.0, at least when tests are enabled, I’m planning to wait for this upcoming release and then update rapidyaml and c4core (from 0.1.11 to 0.2.0) at the same time in Fedora Linux. The current state of `master` works fine, and I did notice https://github.com/biojppm/rapidyaml/pull/425. I don’t see any obstacles to packaging the new release as soon as it is ready.

**Comment by biojppm** [comment]
0.6.0 released
