### ISSUE TITLE
How to get started when the docks are all about bragging and code examples are buried deep and inconsistent?

### ISSUE THREAD

**Issue by jonas-printzen** [biojppm/rapidyaml#429]
Just as a single detail in a big pile of dock-debt.

Examples are documented as namespace `ryml`. The code (conan 2) uses `c4::yml`.

If this is indicative of what to expect as this evolve, I worry that is't hurting users.

**Comment by biojppm** [comment]
It is hard to see what concrete issue you have.

Are you bothered by the `ryml`<->`c4::yml` namespace alias? Is it that its existence is not prominently announced? While the merits or demerits of this alias may be debatable, its existence is something that cannot be changed at this point. Unless you have a better idea. If so, please open a separate issue/PR to address that.
 
Do you think the documentation is scattered? If so, constructive criticism is invited, and concrete suggestions on how to improve are welcome, maybe even a PR. But as it is, your issue is none of the above.

Did you find it hard to locate the complete readthedocs+doxygen documentation?

Did you find it hard to scroll down the main README and locate a really large code sample there?

Is it that you have a problem with the performance claims made in the docs? Should they be in a different place? Should they be buried? Perhaps you think these claims have no place in the docs? That would be just your opinion, and hardly valueable as an issue.

You mention conan. Is your issue with the conan package, or with this library? Did you fail to see the part both in the main README and readthedocs where it says I am not responsible for downstream packages, much less how they are presented? 

Is it all of the above?

Whatever your concrete problem is, your tone comes across as dismissive and unpleasant, and is less than acceptable.

I invite you to open separate constructive issues to address any individual problems you may identify. As it is, this issue is not just unpleasant, it is unworkable. Closing now.
