### ISSUE TITLE
`Tree['...'].key().str` returns an incompletely parsed string value

### ISSUE THREAD

**Issue by andry81** [biojppm/rapidyaml#56]
OS: `Windows 7 x64`
Compiler: `MSVC 2017`

yaml:
```
headers:
  xml1: |
    <?xml version='1.0' encoding='UTF-8'?>
    <mydoc>
  xml2: |
    <?xml version='1.0' encoding='UTF-8'?>

footers:
  xml1: |
    </mydoc>
  xml2: ""

schema:
  - xpath: [mydoc/blabla, blabla]
```

```
ryml::Tree myyaml = ryml::parse(c4::csubstr{ myyaml_str.c_str(), myyaml_str.length() });
std::string a = myyaml["schema"].key().str;
```
After parse the `schema` key is not `schema`. It contains all the text after the colon character: `schema:\n ...`

**Comment by andry81** [comment]
I know the `.len` contains correct value, but the `.str` is a public field and can be passed into C function without the `.len` parameter.

**Comment by biojppm** [comment]
This cannot work:
```c++
std::string a = myyaml["schema"].key().str;  // WRONG.
```
By design, the strings in the ryml tree are NOT zero-terminated. You cannot build a `std::string` directly from `key().str`; that will cause the `std::string` constructor to look for the first \0 which in this case you were lucky to have at the end of the buffer. In the general case there won't even be one, so the std::string ctor may very well overflow and cause a segmentation fault.

Instead build it like this:
```c++
csubstr k = myyaml["schema"].key();
std::string a(k.str, k.len); // provide a count
std::string a(k.begin(), k.end());  // or begin and end
```

**Comment by andry81** [comment]
Yes. But in contrast, the `rapidxml` does write zeros in place and you can use C string directly. It was confusing when I was using the `rapidyaml` after the `rapidxml`.
