### ISSUE TITLE
`is_trivially_copyable` is not member of `std` (GCC < 5)

### ISSUE THREAD

**Issue by andry81** [biojppm/rapidyaml#70]
Here is the issue: https://stackoverflow.com/questions/25123458/is-trivially-copyable-is-not-a-member-of-std
Workaround: https://stackoverflow.com/questions/25123458/is-trivially-copyable-is-not-a-member-of-std/31798726#31798726

**Comment by biojppm** [comment]
Thanks for reporting and special thanks for suggesting a workaround.

gcc earlier than 5 is not supported; this is quite prominent at the top of the README,md. I do know of that workaround; but it is not exactly the same as the original and on top of that, gcc 5 was released in April 2015, so that's why I chose to not support earlier than 5.

But I'm willing to have a go; if it passes the tests, I may adopt it.

**Comment by biojppm** [comment]
@andry81 sorry; this is not the only problem with g++5 (read the comments in the commit above), so at the moment I'm not willing to make the effort to support 4.8/4.9. Out of curiosity, what platform/toolset are you stuck with that forces you to use GCC<5? I ask because if that is a common use case, it would make me more willing to do this.

**Comment by andry81** [comment]
> Out of curiosity, what platform/toolset are you stuck with that forces you to use GCC<5? 
Mostly the old Linux system.
