### ISSUE TITLE
Deserializing "false" leads to NOT IMPLEMENTED error on windows

### ISSUE THREAD

**Issue by Gei0r** [biojppm/rapidyaml#74]
Hi, me again 😉

I suspect this is multiple errors in one. On windows, the following code yields
```
ext/c4core/src/c4/error.cpp:168: ERROR: NOT IMPLEMENTED
```

```C++
#include <ryml.hpp>

int main()
{
    char input[] = "a: false";   // this works:  "a: 0"

    ryml::Tree tree = ryml::parse(c4::substr(input));
    ryml::NodeRef a = tree["a"];

    bool result;   // std::string works (also need to include ryml_std.hpp)
    a >> result;
}
```

Now the ```C4_NOT_IMPLEMENTED()``` comes from `is_debugger_attached()`, which doesn't have a windows implementation. But why the function is triggered in the first place, I don't know.

**Comment by biojppm** [comment]
ryml is still a bit dumb handling types...

What happens is that `>>` will call `c4::from_chars()`. This function has a specialization for strings and a different specialization for integers (of which `bool` is an instance), implemented in terms of `c4::atoi()`.

`"false"` can be read just fine as a string, so that's why you see `>>` succeed with `a: false` and then `std::string`. Also, `"0"` can be read as an integer just fine, so that's why you see `>>` succeed with `a: 0` and then `bool`.

What is missing is a specialization for `bool` that considers `true, false` as valid values.

Thanks for reporting, I will try to address this hopefully in the coming days. 

However, `false`

**Comment by biojppm** [comment]
Just to add this. Until there is a fix, you can workaround possible values of `true` or `false` doing something like this:
```c++
bool result;
if(a.val() == "true") result = true;
else if(a.val() == "false") result = false;
else a >> result; /*assume integer*/
```

**Comment by Gei0r** [comment]
Yeah, I'll just go with
```C++
    bool result = a.val() != "false" && a.val() != "0";
```
in the meantime.

**Comment by biojppm** [comment]
A push fixing this meant to another branch ended up in master. I'm reopening, and will keep this open until that branch is merged.
